name: Kernel CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04-arm
    container: debian:sid

    strategy:
      # Set fail-fast to false to ensure that feedback is delivered for all matrix combinations. Consider changing this to true when your workflow is stable.
      fail-fast: false

    steps:
    - uses: actions/checkout@v4
    - name: Setup LLVM
      run: |
        apt-get update
        apt-get install curl bison flex make binutils dwarves git lld pahole zip perl make llvm python3 python-is-python3 bc libssl-dev libelf-dev clang llvm ccache cpio tar xz-utils -y
    - uses: hendrikmuhs/ccache-action@v1.2
      with:
        create-symlink: true
        key: 11451419190810
        max-size: 1536M

    - name: Configure
      run: make LLVM=1 O=out KCFLAGS+=-Wno-error gki_defconfig vendor/pineapple_GKI.config vendor/oplus/pineapple_GKI.config -j8 >/dev/null
    - name: Build
      run: make LLVM=1 O=out KCFLAGS+=-Wno-error all -j8
    - name: clean
      run: |
        rm -rf -v $(find out -name *.o)
        rm -rf -v $(find out -name *.a)
    - uses: actions/upload-artifact@v4
      with:
        name: boot
        path: out/arch/arm64/boot/Image
    - uses: actions/upload-artifact@v4
      with:
        name: maps
        path: out/System.map
